language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-pygame
  - sudo apt-get install -qq python-pygame
  #- sudo apt-get update -qq
  #- sudo apt-get build-dep -qq python-pygame
  #- sudo apt-get install -qq python-pygame
# command to install dependencies
install:
  - "pip install -r requirements/travis.txt"
  - "pip install ."
  - "pip install coveralls"
# command to run tests
script:
  - py.test tests/*.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  coveralls
