language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-pygame
  - sudo apt-get install -qq python-pygame
# command to install dependencies
install:
  - "pip install -r requirements/travis.txt"
  - "pip install ."
  - "pip install coveralls"
# command to run tests
script:
  coverage run --source=hypatia py.test tests/*.py
after_success:
  coveralls
virtualenv:
    system_site_packages: true
