language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install --allow-external pygame"
  - "pip install -r requirements/base.txt"
  - "pip install -r requirements/python2.txt"
  - "pip install ."
# command to run tests
script: py.test
