= Introduction

== Purpose

This Game Design Document will be started by Tom.

This document describes the development, API requirements for Hypatia Engine.

Game Requirements > Game Engine > API > Code. Then later on we can build Hypatia the game, using Hypatia Engine.


[quote,'http://en.wikipedia.org/wiki/Game-Design-Document[Game Design Document on Wikipedia]']
____
A game design document (often abbreviated GDD) is a highly descriptive living design document of the design for a video game. A GDD is created and edited by the development team and it is primarily used in the video game industry to organize efforts within a development team. The document is created by the development team as result of collaboration between their designers, artists and programmers as a guiding vision which is used throughout the game development process. When a game is commissioned by a game publisher to the development team, the document must be created by the development team and it is often attached to the agreement between publisher and developer; the developer has to adhere to the GDD during game development process.
____

